const video=document.querySelector('#video'),world=document.querySelector('#world'),maskCanvas=document.querySelector('#mask'),ctx=world.getContext('2d',{alpha:false}),mctx=maskCanvas.getContext('2d',{willReadFrequently:true}),stage=document.querySelector('#stage');let W,H,D,stream,segmenter,maskData,live=false,mode='sand',particles=[],lastSeg=0,lastFrame=performance.now(),frames=0,lastFps=0;const MAX=innerWidth<700?9000:15000,MW=160,MH=120;maskCanvas.width=MW;maskCanvas.height=MH;
function resize(){D=Math.min(devicePixelRatio||1,1.5);W=innerWidth;H=innerHeight;world.width=W*D;world.height=H*D;ctx.setTransform(D,0,0,D,0,0)}resize();addEventListener('resize',resize);
document.querySelector('#cameraBtn').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();stage.classList.add('started','loading');segmenter=new SelfieSegmentation({locateFile:f=>'https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/'+f});segmenter.setOptions({modelSelection:1,selfieMode:true});segmenter.onResults(results=>{mctx.save();mctx.clearRect(0,0,MW,MH);mctx.translate(MW,0);mctx.scale(-1,1);mctx.drawImage(results.segmentationMask,0,0,MW,MH);mctx.restore();maskData=mctx.getImageData(0,0,MW,MH).data;live=true;stage.classList.remove('loading');stage.classList.add('live')});await segmenter.send({image:video});requestAnimationFrame(loop)}catch(e){document.querySelector('#start p').textContent='Camera could not start. This needs HTTPS and camera permission.'}};
function solid(x,y){if(!maskData||x<0||y<0||x>=W||y>=H)return false;let mx=Math.floor(x/W*MW),my=Math.floor(y/H*MH);return maskData[(my*MW+mx)*4+3]>105}
function spawn(n){for(let k=0;k<n&&particles.length<MAX;k++){let storm=mode==='storm',light=mode==='snow';particles.push({x:Math.random()*W,y:-10-Math.random()*90,vx:(Math.random()-.5)*(storm?4:.7),vy:1+Math.random()*(storm?5:2),r:light?1+Math.random()*2:.7+Math.random()*1.6,a:.5+Math.random()*.5,h:Math.random()})}}
function physics(p){let ox=p.x,oy=p.y;p.vy+=mode==='snow'?.012:.075;p.vx*=.997;p.vy=Math.min(p.vy,mode==='storm'?12:7);let nx=p.x+p.vx,ny=p.y+p.vy;if(solid(nx,ny)){let left=solid(nx-5,ny),right=solid(nx+5,ny),above=solid(nx,ny-6);if(!left){p.vx-=.28+Math.random()*.35;p.vy*=.25}else if(!right){p.vx+=.28+Math.random()*.35;p.vy*=.25}else{p.vy=-Math.abs(p.vy)*(.08+Math.random()*.12);p.vx+=(Math.random()-.5)*.35}p.x=ox;p.y=oy}else{p.x=nx;p.y=ny}if(p.x<-20)p.x=W+10;if(p.x>W+20)p.x=-10}
function drawCamera(){ctx.save();ctx.translate(W,0);ctx.scale(-1,1);let vr=video.videoWidth/video.videoHeight,cr=W/H,sx=0,sy=0,sw=video.videoWidth,sh=video.videoHeight;if(vr>cr){sw=video.videoHeight*cr;sx=(video.videoWidth-sw)/2}else{sh=video.videoWidth/cr;sy=(video.videoHeight-sh)/2}ctx.globalAlpha=.27;ctx.filter='grayscale(1) contrast(1.25) brightness(.72)';ctx.drawImage(video,sx,sy,sw,sh,0,0,W,H);ctx.restore();ctx.filter='none';ctx.globalAlpha=1;ctx.fillStyle='rgba(2,5,4,.28)';ctx.fillRect(0,0,W,H)}
function silhouette(){if(!maskData)return;let img=mctx.getImageData(0,0,MW,MH),d=img.data;for(let i=0;i<d.length;i+=4){let a=d[i+3];d[i]=80;d[i+1]=112;d[i+2]=101;d[i+3]=a*.12}let tmp=document.createElement('canvas');tmp.width=MW;tmp.height=MH;tmp.getContext('2d').putImageData(img,0,0);ctx.globalCompositeOperation='screen';ctx.drawImage(tmp,0,0,W,H);ctx.globalCompositeOperation='source-over'}
async function loop(t){if(!live){if(segmenter&&video.readyState>=2&&t-lastSeg>80){lastSeg=t;try{await segmenter.send({image:video})}catch{}}requestAnimationFrame(loop);return}if(video.readyState>=2&&t-lastSeg>75){lastSeg=t;segmenter.send({image:video}).catch(()=>{})}drawCamera();silhouette();spawn(mode==='storm'?42:mode==='snow'?18:30);for(let i=particles.length-1;i>=0;i--){let p=particles[i];physics(p);if(p.y>H+30){particles.splice(i,1);continue}let col=mode==='snow'?'225,235,229':mode==='storm'?'209,154,75':'223,190,125';ctx.fillStyle='rgba('+col+','+p.a+')';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();if(p.r>1.5){ctx.fillStyle='rgba('+col+',.08)';ctx.beginPath();ctx.arc(p.x,p.y,p.r*3.2,0,Math.PI*2);ctx.fill()}}document.querySelector('#count').textContent=particles.length.toLocaleString();frames++;if(t-lastFrame>1000){lastFps=frames;frames=0;lastFrame=t;document.querySelector('#fps').textContent=lastFps}requestAnimationFrame(loop)}
document.querySelectorAll('#controls [data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('#controls [data-mode]').forEach(x=>x.classList.toggle('on',x===b))});document.querySelector('#clear').onclick=()=>particles.length=0;