export async function createGPUMatter(canvas,{count=100000}={}){
 if(!navigator.gpu)throw new Error('WebGPU unavailable');
 const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)throw new Error('No GPU adapter');
 const device=await adapter.requestDevice(),ctx=canvas.getContext('webgpu'),format=navigator.gpu.getPreferredCanvasFormat();
 const d=Math.min(devicePixelRatio||1,1.5);function resize(){let r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.configure({device,format,alphaMode:'premultiplied'})}resize();
 const stride=8,bytes=count*stride*4,data=new Float32Array(count*stride);
 for(let i=0;i<count;i++){let k=i*stride;data[k]=Math.random()*2-1;data[k+1]=Math.random()*2.2;data[k+2]=(Math.random()-.5)*.002;data[k+3]=-Math.random()*.006;data[k+4]=Math.random();data[k+5]=Math.random();data[k+6]=Math.random();data[k+7]=1}
 const particles=device.createBuffer({size:bytes,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(particles,0,data);
 const uniform=device.createBuffer({size:128,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});
 const shader=device.createShaderModule({code:`
 struct P{pos:vec2f,vel:vec2f,misc:vec4f}; struct U{meta:vec4f,h0:vec4f,h1:vec4f,v0:vec4f,v1:vec4f,p0:vec4f,p1:vec4f,imp:vec4f};
 @group(0) @binding(0) var<storage,read_write> p:array<P>; @group(0) @binding(1) var<uniform> u:U;
 @compute @workgroup_size(256) fn step(@builtin(global_invocation_id) id:vec3u){let i=id.x;if(i>=${count}u){return;}var q=p[i];if(u.meta.z==0.){q.vel.y-=.000055;}else if(u.meta.z==1.){q.vel.y+=.000025;q.vel.x+=sin(f32(i)*.17+q.pos.y*8.)*.000018;}else{let rr=max(length(q.pos),.05);q.vel+=vec2f(-q.pos.y,q.pos.x)/rr*.000065;q.vel+=vec2f(sin(f32(i)*.11),cos(f32(i)*.07))*.000025;}for(var j=0u;j<2u;j++){if(f32(j)>=u.meta.w){break;}let h=select(u.h0,u.h1,j==1u);let hv=select(u.v0,u.v1,j==1u);let pn=select(u.p0,u.p1,j==1u);let d=vec2f((q.pos.x-h.x)*u.meta.y,q.pos.y-h.y);let L=max(length(d),.001);if(L<h.z){let force=(1.-L/h.z)*.0028;q.vel+=vec2f(normalize(d).x/u.meta.y,normalize(d).y)*force;q.vel+=hv.xy*.00025;if(pn.z>0.5&&distance(q.pos,pn.xy)<h.z*.22){q.vel*=.7;q.pos=mix(q.pos,pn.xy,.32);}else if(h.w>0.5&&L<h.z*.72){q.vel*=.86;q.pos=mix(q.pos,h.xy+(q.pos-h.xy)*.2,.11);}else if(hv.w>.38&&L<h.z*.88){q.vel+=(h.xy-q.pos)*.00018*hv.w;}}}if(u.meta.w>1.5){let mid=(u.h0.xy+u.h1.xy)*.5;let span=distance(u.h0.xy,u.h1.xy);let d=q.pos-mid;let L=max(length(d),.001);if(span<.48&&L<.42){q.vel-=normalize(d)*(.48-span)*.0003;}}if(u.imp.x>.01){let origin=u.imp.yz;let d=q.pos-origin;let L=max(length(d),.001);if(L<.8){q.vel+=normalize(d)*u.imp.x*.006*(1.-L/.8);}}q.pos+=q.vel;if(u.meta.z==0.){let floor=-.96+q.misc.x*.10;if(q.pos.y<floor){q.pos.y=floor;q.vel.y=abs(q.vel.y)*.06;q.vel.x*=.82;}}if(q.pos.y< -1.15||q.pos.y>1.22||abs(q.pos.x)>1.3){q.pos=vec2f(fract(sin(f32(i)*12.9898)*43758.5453)*2.-1.,1.12);q.vel=vec2f(0.,-.0015-fract(sin(f32(i)*4.13)*911.1)*.004);}q.vel*=.999;p[i]=q;}
 struct O{@builtin(position) pos:vec4f,@location(0) life:f32,@location(1) uv:vec2f}; @vertex fn vs(@builtin(vertex_index) vi:u32,@builtin(instance_index) ii:u32)->O{let q=p[ii];let cs=array<vec2f,6>(vec2f(-1.,-1.),vec2f(1.,-1.),vec2f(-1.,1.),vec2f(-1.,1.),vec2f(1.,-1.),vec2f(1.,1.));let c=cs[vi];let z=.003+q.misc.x*.0035;var o:O;o.pos=vec4f(q.pos+vec2f(c.x/u.meta.y,c.y)*z,0.,1.);o.life=q.misc.x;o.uv=c;return o;}
 @fragment fn fs(i:O)->@location(0) vec4f{let r=length(i.uv);if(r>1.){discard;}let a=(1.-smoothstep(.2,1.,r))*.78;let sand=vec3f(.89,.74+.15*i.life,.43+.35*i.life);let light=vec3f(.62+.25*i.life,.82,.98);let storm=vec3f(.72,.58+.22*i.life,.38+.18*i.life);let col=select(select(sand,light,u.meta.z==1.),storm,u.meta.z==2.);return vec4f(col,a);}
 `});
 const computeBgl=device.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.COMPUTE,buffer:{type:'storage'}},{binding:1,visibility:GPUShaderStage.COMPUTE,buffer:{type:'uniform'}}]});
 const renderBgl=device.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX,buffer:{type:'read-only-storage'}},{binding:1,visibility:GPUShaderStage.VERTEX,buffer:{type:'uniform'}}]});
 const computeLayout=device.createPipelineLayout({bindGroupLayouts:[computeBgl]}),renderLayout=device.createPipelineLayout({bindGroupLayouts:[renderBgl]});
 const compute=await device.createComputePipelineAsync({layout:computeLayout,compute:{module:shader,entryPoint:'step'}});
 const render=await device.createRenderPipelineAsync({layout:renderLayout,vertex:{module:shader,entryPoint:'vs'},fragment:{module:shader,entryPoint:'fs',targets:[{format,blend:{color:{srcFactor:'src-alpha',dstFactor:'one',operation:'add'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha',operation:'add'}}}]},primitive:{topology:'triangle-list'}});
 const computeBg=device.createBindGroup({layout:computeBgl,entries:[{binding:0,resource:{buffer:particles}},{binding:1,resource:{buffer:uniform}}]}),renderBg=device.createBindGroup({layout:renderBgl,entries:[{binding:0,resource:{buffer:particles}},{binding:1,resource:{buffer:uniform}}]});
 let alive=true,last=performance.now(),state={mode:0,hands:[]},impulse=0,impulsePos=null,previous=[],raf=0;device.lost.then(()=>{alive=false;cancelAnimationFrame(raf)}).catch(()=>{});
 function frame(now){if(!alive)return;let r=canvas.getBoundingClientRect();if(canvas.width!==Math.floor(r.width*d)||canvas.height!==Math.floor(r.height*d))resize();let dt=Math.min(.033,(now-last)/1000);last=now,aspect=r.width/r.height;
  let a=new Float32Array(32);a[0]=dt;a[1]=aspect;a[2]=state.mode;a[3]=Math.min(2,state.hands.length);state.hands.slice(0,2).forEach((h,i)=>{let k=4+i*4;a[k]=(h.x/r.width)*2-1;a[k+1]=1-(h.y/r.height)*2;a[k+2]=Math.max(.06,h.size/r.height*1.35);a[k+3]=h.closed?1:0;let v=12+i*4;a[v]=(h.vx||0)/r.width;a[v+1]=-(h.vy||0)/r.height;a[v+2]=Math.hypot(h.vx||0,h.vy||0)/Math.max(r.width,r.height);a[v+3]=h.cup||0;let p=20+i*4;a[p]=((h.pinchX??h.x)/r.width)*2-1;a[p+1]=1-((h.pinchY??h.y)/r.height)*2;a[p+2]=h.pinching?1:0;a[p+3]=h.pinchStrength||0});a[28]=impulse;a[29]=impulsePos?impulsePos.x/r.width*2-1:0;a[30]=impulsePos?1-impulsePos.y/r.height*2:0;impulse*=.82;if(impulse<.02)impulsePos=null;device.queue.writeBuffer(uniform,0,a);
  let enc=device.createCommandEncoder(),cp=enc.beginComputePass();cp.setPipeline(compute);cp.setBindGroup(0,computeBg);cp.dispatchWorkgroups(Math.ceil(count/256));cp.end();
  let rp=enc.beginRenderPass({colorAttachments:[{view:ctx.getCurrentTexture().createView(),clearValue:{r:0,g:0,b:0,a:0},loadOp:'clear',storeOp:'store'}]});rp.setPipeline(render);rp.setBindGroup(0,renderBg);rp.draw(6,count);rp.end();device.queue.submit([enc.finish()]);raf=requestAnimationFrame(frame)}
 raf=requestAnimationFrame(frame);return{setHands(h){previous=state.hands;state.hands=h||[];if(previous.length===2&&state.hands.length===2){let old=Math.hypot(previous[0].x-previous[1].x,previous[0].y-previous[1].y),now=Math.hypot(state.hands[0].x-state.hands[1].x,state.hands[0].y-state.hands[1].y);if(old<150&&now>old+35)impulse=Math.min(.9,(now-old)/100)}},setMode:m=>state.mode=m==='light'?1:m==='storm'?2:0,burst:(p=.65,x,y)=>{impulse=Math.max(impulse,p);if(Number.isFinite(x)&&Number.isFinite(y))impulsePos={x,y}},destroy:()=>{alive=false;cancelAnimationFrame(raf);try{particles.destroy();uniform.destroy()}catch{}}}
}