import fs from 'node:fs';
const app=fs.readFileSync('app.js','utf8'),html=fs.readFileSync('index.html','utf8'),gpu=fs.readFileSync('gpu-matter.js','utf8');
const fail=m=>{throw new Error(m)};
if(!app.startsWith("const $=s=>document.querySelector(s),all=s=>"))fail('selector helpers broken');
if(app.includes("$('.view').forEach"))fail('route incorrectly uses single-element selector for view collection');
if(!app.includes("all('.view').forEach"))fail('route view collection missing');
for(const id of ['room','home','body','trails','voice','move','future','mirror'])if(!html.includes('id="'+id+'"'))fail('missing route '+id);
for(const id of ['roomStart','bodyStart','micBtn','motionBtn','buildBtn','mirrorStart','shareLab','passPanel'])if(!html.includes('id="'+id+'"')||!app.includes("'#"+id+"'"))fail('unwired control '+id);
if(!html.includes('@mediapipe/hands/hands.js')||!html.includes('@mediapipe/selfie_segmentation/selfie_segmentation.js'))fail('vision libraries missing');
if(!gpu.includes('device.lost')||!gpu.includes('cancelAnimationFrame(raf)'))fail('GPU lifecycle guard missing');
if(!app.includes('CLAP SHOCKWAVE')||!app.includes('PALM WIND'))fail('BODY gesture physics missing');
if(!app.includes('bt-artifact-seed')||!app.includes('totals:{'))fail('artifact lineage missing');
if(!app.includes("impossible-room-v1")||!app.includes("THE ROOM REMEMBERS YOU"))fail('Room memory missing');
if(!app.includes("memory.learned.push('THROW')")||!app.includes("memory.learned.push('PINCH')"))fail('Room learned gestures missing');
if(!app.includes("CUSTOM:")||!app.includes("SOMETHING LEARNED YOU")||!app.includes("pred.push"))fail('Room adaptive intelligence missing');
if(!app.includes("YOU CAUGHT IT")||!app.includes("past.push")||!app.includes("YOU THREW SOMETHING THAT ISN’T THERE"))fail('Room impossible object or temporal selves missing');
if(!app.includes("YOUR VOICE MADE SOMETHING")||!app.includes("VOICEBORN")||!app.includes("temper.fear")||!app.includes("temper.trust"))fail('Room voice species or behavioral memory missing');
if(!html.includes('id="roomPass"')||!html.includes('id="roomMemory"'))fail('Room lineage UI missing');
console.log('Static invariants OK');

if(!html.includes('roomMind')||!app.includes('runHypothesis')||!app.includes('Correction accepted')||!app.includes('CONFIDENCE '))fail('Room reasoning feedback loop missing');
